#Server port
server.port= 8900

#Application name
spring.application.name= api-gateway

#Client registration options :
eureka.client.service-url.defaultZone = http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

zuul.prefix=/api
zuul.ignored-services=*

# Map paths to services
#----------------------------------
# User service :
zuul.routes.userservice.path=/accounts/**
zuul.routes.userservice.service-id=user-service

# Catalog service :
zuul.routes.catalogservice.path=/catalog/**
zuul.routes.catalogservice.service-id=product-catalog-service

# Order service :
zuul.routes.orderservice.path=/shop/**
zuul.routes.orderservice.service-id=order-service

# Recommendation service :
zuul.routes.recommendationservice.path=/review/**
zuul.routes.recommendationservice.service-id=product-recommendation-service

#SPRING SESSION & REDIS PROPERTIES :
#-------------------------------
spring.session.store-type=none
spring.session.redis.namespace=session
spring.session.redis.flush-mode=on-save
spring.redis.host=localhost
spring.redis.port=6379

#SECURITY
#---------------------------------
zuul.sensitive-headers=

# Max Request Size for Base64 Images
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-http-post-size=50MB

# Timeouts for large uploads
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=60000
ribbon.ConnectTimeout=60000
ribbon.ReadTimeout=60000
zuul.host.connect-timeout-millis=60000
zuul.host.socket-timeout-millis=60000



